
services:
  bd:
    container_name: bd
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fsdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  bdcli:
    container_name: bdcli
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      bd:
          condition: service_healthy
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    restart: always
    ports:
      - "3000:4000"
    environment:
      - database_url=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bd/${POSTGRES_DB}
      - jwt_secret_key=${JWT_SECRET_KEY}
      - seed_demo_data=${SEED_DEMO_DATA:-true}
    depends_on:
      bd:
          condition: service_healthy
    volumes:
      - ./backend:/app

volumes:
  pgdata: {}
