services:
  bot:
    container_name: saludplus-bot
    build:
      context: .
      dockerfile: bot.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
